export const SET_AIR_INDEX = 'SET_AIR_INDEX';
export const SET_AIR_TRANSITION = 'SET_AIR_TRANSITION';
export const SET_NAMESAKE = 'SET_NAMESAKE';
export const SET_NAMESAKE_TRANSITION = 'SET_NAMESAKE_TRANSITION';
